export WORKSPACE=${WORKSPACE:-/workspace}

export APPZ=/usr/local/apps
export ARCHFLAGS="-arch x86_64"
export CATALINA_HOME=/usr/local/share/tomcat
export COMPANY=${COMPANY:-thirteensystems}
export CONDA_HOME=/opt/conda
export PROJECT=${PROJECT:-daedalus}
export CONTEXT=${CONTEXT:-${COMPANY}/${PROJECT}}
export EDITOR=vim
export ENV=`uname`
export ENVIRONMENT=${ENVIRONMENT:-${WORKSPACE}/dotfiles}
export FORCE_COLOR=1
export GIT_EDITOR=vim
export HISTSIZE=5000
export JAVA_HOME=/usr/local/share/java
export LESS="-RXF"
export PROMPT_COMMAND='history -a'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export NODE_MODULES=`realpath ~/.node_modules`
export NODE_OPTIONS=--max-old-space-size=8192
export NVM_HOME=`realpath ~/.nvm`
export OPER=/usr/local/oper
export PAGER=most
export PNPM_HOME=`realpath ~/.local/share/pnpm`
export PYENV_ROOT=`realpath ~/.pyenv`
export PYTHONUNBUFFERED=1
export SVN_EDITOR=vim
export VISUAL=${EDITOR}
export WINDOWS=${WINDIR}/System32
